### PR TITLE
Feature/better visualisation

### PR DESCRIPTION
**Pull request by mazzeaar**
There is still an error, but at least it runs...
Merging so we can start improving.

### CODE REVIEW

**Review by casparschucan — CHANGES_REQUESTED** [review]
I'd love to see 3 changes
in experiment.sh change line 29 to
```
mpiexec -n "$NUM_PROCESSORS" --use-hwthread-cpus "$TEST_EXE"
```
and in Orthotree.hpp in the print to file functions when creating the ofstreams (hilarious class name btw)

```
std::ofstream file(outputPath, std::ofstream::out);
```
also on my system the script isn't able to create the output directory can we add that too?

**Comment by mazzeaar** [comment]
> and in Orthotree.hpp in the print to file functions when creating the ofstreams (hilarious class name btw)

i never noticed that, thank you💀

**Comment by mazzeaar** [comment]
changes are implemented:) just merge this pr if you are ok with it

**Review by casparschucan — APPROVED** [review]
lgtm

**Pull request merged**
